* Introduction
* Installation
* Usage
* Examples

*** Book 1 author
    Медведев В. В. Мониторинг почв Украины / В. В. Медведев. — Харьков : Міськдрук, 2012. — 535 с.

*** Book 2 authors

    Беспамятнов Г. П. Предельно-допустимые концентрации химических веществ в окружающей среде: Справочник / Г. П. Беспамятнов, Ю. А. Кротов. — Ленинград : Химия, 1985. — 528 с.

*** Book 3 authors

    Сает Ю. Е. Геохимия окружающей среды / Ю. Е. Сает, Б. А. Ревич, Е. П. Янин. — Москва : Недра, 1990. — 335 с.

*** Book 4 authors

    Важкі метали: надходження в ґрунти, транслокація у рослинах та екологічна небезпека / В. М. Гришко, Д. В. Сищиков, О. М. Піскова та ін. — Донецьк : Донбас, 2012. — 304 с.

*** Book 5 and more authors

    Теоретические основы и пути регулирования плодородия почв / Л. Л. Шишов, Д. Н. Дурманов, И. И. Карманов, В. В. Ефремов. — Москва : ВО «Агропромиздат», 1991. — 304 с.

*** Journal article 1 author

    Яковлєв В. В. Джерельні води Харківської області як джерело питного водопостачання / В. В. Яковлєв // Вісник Харківського національного університету імені В.Н. Каразіна. — 2014. — № 40 (1098). — С. 63–72.

*** Journal article 2 authors

    Семчук Ю. С. Геостатистичний аналіз забруднення ґрунтових вод за даними спостережень якості колодязної води регіону / Ю. С. Семчук, А. Р. Ящолт // Вісник Вінницького політехнічного інституту. — 2013. — № 3. — С. 17–21.

*** Journal article 3 authors

    Смирнова С. М. Оцінка можливості використання підземних джерел води в якості питної води на прикладі мікрорайону Терновка міста Миколаєва / С. М. Смирнова, В. М. Смирнов, Д. В. Багатюк // Науковий вісник Миколаївського державного університету імені В.О. Сухомлинського. — 2014. — № 2. — С. 57–63.

*** Journal article 4 authors

    Національна екологічна безпека та екологічна паспортизація водних об’єктів / В. Гончарук, Г. Білявський, М. Ковальов, Г. Рубцов // Вісник Національної академії наук України. — 2009. — № 5. — С. 22–29.

*** Journal article 5 and more authors

    Медико-біологічна оцінка якості та цінності підземних вод джерел № 1, 4–10 у с. Лотатники Стрийського району Львівської області щодо обґрунтування можливості їх фасування / О. Нікіпелова, С. Леонова, Л. Горбач та ін. // Науковий вісник Східноєвропейського національного університету імені Лесі Українки. Географічні науки. — 2013. — № 16. — С. 17–23.

*** Norms and standards

    Визначення забруднення ґрунтів навколо бурових площадок (методичні вказівки) : КНД 41-00032626-00-326–99. — [Чинний від 1999-04-24]. — Київ : Держкомекології, 1999. — 46 с. — (Керівний нормативний документ).
    Якість ґрунту. Показники родючості ґрунтів : ДСТУ 4362:2004. — [Чинний від 2004-12-09]. — Київ : Держспоживстандарт України, 2006. — 28 с. — (Національний стандарт України).
