* Вступ

  З давніх-давен складання списку літератури було нудною і копіткою роботою.
  Особливо на теренах Східної Європи, де з не менш давніх давен буквоїдство є
  одним із найулюбленіших занять чиновників Міністерства освіти (та й не лише
  його). Національний стандарт ДСТУ ГОСТ 7.1 2006 -- вершина невгамовного
  ентузіазму й самовідданої жертовної праці багатьох поколінь службовців (і
  науковців) різних рангів -- ще до сьогодні щорічно викликає приступи панічної
  гикавки у майбутніх аспірантів та, мабуть, в однаковій мірі й у докторанів.
  Слід відзначити, що ДСТУ ГОСТ 7.1 2006 не є унікальною розробкою, ані ноу-хау,
  східноєвропейців. Як і більшість усього хорошого і поганого, ДСТУ ГОСТ 7.1
  2006 є досягненням наших західних партнерів і візаві (кому як більше до
  вподоби), і у Західному світі відомий під назвою "[[https://uk.wikipedia.org/wiki/%25D0%259C%25D1%2596%25D0%25B6%25D0%25BD%25D0%25B0%25D1%2580%25D0%25BE%25D0%25B4%25D0%25BD%25D0%25B8%25D0%25B9_%25D1%2581%25D1%2582%25D0%25B0%25D0%25BD%25D0%25B4%25D0%25B0%25D1%2580%25D1%2582%25D0%25BD%25D0%25B8%25D0%25B9_%25D0%25B1%25D1%2596%25D0%25B1%25D0%25BB%25D1%2596%25D0%25BE%25D0%25B3%25D1%2580%25D0%25B0%25D1%2584%25D1%2596%25D1%2587%25D0%25BD%25D0%25B8%25D0%25B9_%25D0%25BE%25D0%25BF%25D0%25B8%25D1%2581][Міжнародний стандартний
  бібліографічний опис]]". Власне вітчизняним досягненням є офіційна вимога
  використовувати його при підготовці наукових публікацій, зокрема дисертацій на
  здобуття наукових ступенів кандидатів і докторів наук.

  В наш час стрімкого розвитку інформаційних технологій важливою і актуальною
  задачею є максимальна комп'ютеризація і автоматизація нелегкої праці
  науковця. З появою персональних програмних систем збору та каталогізації
  бібліографічної інформації -- "менеджерів посилань" -- таких як [[https://www.zotero.org/][Zotero]], [[http://www.jabref.org/][JabRef]],
  [[https://www.mendeley.com/][Mendeley]], [[http://papersapp.com/][Papers]] та ін., процес підготовки наукової публікації вийшов на
  якісно новий рівень. Ціла епоха відійшла у вічність, адже більше не потрібно
  витрачати десятки людино-годин на перевірку рукопису на предмет хибних
  посилань, чи то їхню відсутність, чи то зайву присутність, не кажучи уже про
  усі ці крапки та тире в бібліографії. Програма, простими словами, робить усе
  автоматично, а науковець може зосередитися на власне науковій роботі. Особливо
  якщо мова йде про таку ґрунтовну роботу, як дисертаційна, яка не рідко може
  містити понад сотню -- а то й дві -- бібліографічних посилань.

  В процесі підготовки дисертаційної я, на моє превелике здивування, не зміг
  знайти бібліографічного стилю для свого улюбленого менеджера посилань, який би
  відповідав вимогам ДСТУ ГОСТ 7.1 2006. Отже постало завдання розробки такого
  стилю, що і було досягнено, і результат чого представлено тут у загальний
  доступ. Відповідний файл був завантажений у Всесвітню мережу Інтернет вже
  понад 5 років тому, проте в силу різних причин, найперше через непотрібність
  мені самому, подальша робота над ним не проводилася. Від тепер ситуація
  змінилася і[[http://citationstyles.org/][ CSL-стиль]] для ДСТУ ГОСТ 7.1 2006 житиме в цьому репозиторії на
  GitHub. Усі бажаючі мають змогу його завантажити безкоштовно без СМС та
  використовувати його у своїй роботі.

  Велике прохання - усі зауваження та побажання надсилати через систему GitHub,
  викорстовуючи інструменти Issues та Pull request, а не мені на пошту.
  Дякую і приємного використання.

* Встановлення

  Завантажити файл 'dstu-gost-7-1-2006.Cal' на персональний комп'ютер, далі
  згідно інструкцій Вашого менеджера посилань.

* Інструкція з використання

  На жаль, [[docs.citationstyles.org/en/stable/specification.html][Citation Style Language (CSL)]] не володіє усіма необхідними засобами для
  прозорої імплементації вимог ДСТУ ГОСТ 7.1 2006, і навряд чи коли-небудь
  буде. Тому довелося вдатися до деяких обхідних шляхів, а користувачам
  потрібно буде дотримуватися деяких правил при каталогізації бібліографії у
  Zotero. До речі, ця інструкція стосується лише Zotero і необов'язково буде
  (хоч і не виключено, що таки буде) працювати у Mendeley та аналогах. Якщо є
  потреба в Mendeley, відкривайте заявки.

*** Що працює

    - Стаття (Journal Article)

      Згідно стандарту, якщо авторів менше чотирьох, то ім'я першого автора
      повинно стояти також на початку опису, перед назвою документа. В CSL немає
      можливості перевірити кількість авторів, тому потрібно якимось чином явно
      вказати що авторів менше чотирьох (або більше трьох). Для цього тут
      використовується поле "Call Number", яке на практиці рідко
      використовується за призначенням. На жаль, як це поле називається в
      українському інтерфейсі я не знаю. Якщо поле пусте, значить авторів менше
      чотирьох, і ім'я першого автору буде стояти на початку. Отже, якщо поле не
      пусте (присутній хоча б один знак), значить авторів чотири або більше, і
      бібліографічний опис починається з назви статті.

     |-------------+----------|
     | Поле        | Значення |
     |-------------+----------|
     | Call Number | +        |
     |-------------+----------|

    - Книга (Book)

      Див. вище.

    - Розділ книги (Book chapter)

      Див. вище.

    - Стандарт (Statute)

      В CSL (і Zotero) немає відповідного типу, тому довелося шукати заміну і використовувати тип Statute.

      Мінімальна форма посилання на ДСТУ ГОСТ 7.1 2006 згідно ДСТУ ГОСТ 7.1 2006
      повинно виглядати наступним чином:

      #+BEGIN_EXAMPLE
      Бібліографічний запис. Бібліографічний опис. Загальні вимоги та правила
      складання : ДСТУ ГОСТ 7.1:2006. — [Чинний від 2007-07-01]. — Київ :
      Держспоживстандарт України, 2007. — 47 с. — (Національний стандарт
      України).
      #+END_EXAMPLE

      Вигляд запису в Zotero:

      |-------------------+------------------------------------------------------------------------------------|
      | Поле              | Значення                                                                           |
      |-------------------+------------------------------------------------------------------------------------|
      | Item Type         | Statute                                                                            |
      | Name of Act       | Бібліографічний запис. Бібліографічний опис. Загальні вимоги та правила  складання |
      | Code              | Національний стандарт України                                                      |
      | Code Number       | ДСТУ ГОСТ                                                                          |
      | Public Law Number | 7.1:2006                                                                           |
      | Date Enacted      | 2007-07-01                                                                         |
      | Pages             | 47                                                                                 |
      | Section           | Київ                                                                               |
      | Session           | Держспоживстандарт України                                                         |
      | History           | 2007                                                                               |
      |-------------------+------------------------------------------------------------------------------------|

*** Що працює, але скоріш за все не повністю чи не так як потрібно

    Усе інше.


* Приклади

  Дякую Дмитрий Д. за наданий список прикладів

*** Книги
***** Один автор

      - Медведев В. В. Мониторинг почв Украины / В. В. Медведев. — Харьков : Міськдрук, 2012. — 535 с.

***** Два автори

      - Беспамятнов Г. П. Предельно-допустимые концентрации химических веществ в окружающей среде: Справочник / Г. П. Беспамятнов, Ю. А. Кротов. — Ленинград : Химия, 1985. — 528 с.

***** Три автори

      - Сает Ю. Е. Геохимия окружающей среды / Ю. Е. Сает, Б. А. Ревич, Е. П. Янин. — Москва : Недра, 1990. — 335 с.

***** Чотири автори

      - Важкі метали: надходження в ґрунти, транслокація у рослинах та екологічна небезпека / В. М. Гришко, Д. В. Сищиков, О. М. Піскова та ін. — Донецьк : Донбас, 2012. — 304 с.

***** П'ять та більше авторів

      - Теоретические основы и пути регулирования плодородия почв / Л. Л. Шишов, Д. Н. Дурманов, И. И. Карманов, В. В. Ефремов. — Москва : ВО «Агропромиздат», 1991. — 304 с.

*** Статті з періодичних видань
***** Один автор

      - Яковлєв В. В. Джерельні води Харківської області як джерело питного водопостачання / В. В. Яковлєв // Вісник Харківського національного університету імені В.Н. Каразіна. — 2014. — Вип. 40, № 1098. — С. 63–72.

***** Два автори

      - Семчук Ю. С. Геостатистичний аналіз забруднення ґрунтових вод за даними спостережень якості колодязної води регіону / Ю. С. Семчук, А. Р. Ящолт // Вісник Вінницького політехнічного інституту. — 2013. — № 3. — С. 17–21.

***** Три автори

      - Смирнова С. М. Оцінка можливості використання підземних джерел води в якості питної води на прикладі мікрорайону Терновка міста Миколаєва / С. М. Смирнова, В. М. Смирнов, Д. В. Багатюк // Науковий вісник Миколаївського державного університету імені В.О. Сухомлинського. — 2014. — № 2. — С. 57–63.

***** Чотири автори

      - Національна екологічна безпека та екологічна паспортизація водних об’єктів / В. Гончарук, Г. Білявський, М. Ковальов, Г. Рубцов // Вісник Національної академії наук України. — 2009. — № 5. — С. 22–29.

***** П'ять та більше авторів

      - Медико-біологічна оцінка якості та цінності підземних вод джерел № 1, 4–10 у с. Лотатники Стрийського району Львівської області щодо обґрунтування можливості їх фасування / О. Нікіпелова, С. Леонова, Л. Горбач та ін. // Науковий вісник Східноєвропейського національного університету імені Лесі Українки. Географічні науки. — 2013. — № 16. — С. 17–23.

*** Стандарти

    - Визначення забруднення ґрунтів навколо бурових площадок (методичні
      вказівки) : КНД 41-00032626-00-326–99. — [Чинний від 1999-04-24]. —
      Київ : Держкомекології, 1999. — 46 с. — (Керівний нормативний документ).
    - Якість ґрунту. Показники родючості ґрунтів : ДСТУ 4362:2004. — [Чинний
      від 2004-12-09]. — Київ : Держспоживстандарт України, 2006. — 28 с. —
      (Національний стандарт України).

* Авторські права та ліцензія

  Михайло Шевчук (C) 2011-2017, Creative Commons Attribution-Share Alike 4.0
  License: http://creativecommons.org/licenses/by-sa/4.0/
